// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCACdDYDKizgwpLJE9yWUw8nmDV6x-YMag',
    appId: '1:163437078198:web:52e5e4c99fb6d6af7d6817',
    messagingSenderId: '163437078198',
    projectId: 'crud-archi',
    authDomain: 'crud-archi.firebaseapp.com',
    storageBucket: 'crud-archi.appspot.com',
    measurementId: 'G-QTKLY9SYMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvjrcM9YXIumStii9-ef47_Me2EEBQXUA',
    appId: '1:163437078198:android:70ecc546e88f163a7d6817',
    messagingSenderId: '163437078198',
    projectId: 'crud-archi',
    storageBucket: 'crud-archi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF_ClhMnGdN717J43p-VjX80knIGRlTSk',
    appId: '1:163437078198:ios:e895d16a020c6f057d6817',
    messagingSenderId: '163437078198',
    projectId: 'crud-archi',
    storageBucket: 'crud-archi.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF_ClhMnGdN717J43p-VjX80knIGRlTSk',
    appId: '1:163437078198:ios:58a802af4ef5bf027d6817',
    messagingSenderId: '163437078198',
    projectId: 'crud-archi',
    storageBucket: 'crud-archi.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
